name: manual release pypi
on: [workflow_dispatch]

env:
  PACKAGE_NAME: pymer4

defaults:
  run:
    # login shell to source the conda hook in .bash_profile
    shell:
      bash -l {0}

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py_ver: [3.8]
        os: [ubuntu-latest]

    steps:
      # ------------------------------------------------------------
      # Step up miniconda
      - name: Download Miniconda
        uses: conda-incubator/setup-miniconda@059455a698430d8b68fa317268fa2e3da3492a98
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.py_ver }}

      # ------------------------------------------------------------
      # Get code
      - name: Checkout code
        uses: actions/checkout@v2
      # ------------------------------------------------------------
      - name: Build and deploy to Pypi
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/

      # 7. Deploy package to Pypi (only need to do this once on linux)
      - name: PyPi deploy
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
